### ISSUE TITLE
Add ability to change Azure resource deployment location

### ISSUE THREAD

**Issue by PlagueHO** [PowerShell/DscConfiguration.Tests#20]
Some Azure subscriptions don't allow VM's in some locations depending on the tier.

For example:
https://ci.appveyor.com/project/PlagueHO/dockerenterprisedscconfig/build/1.0.6.0#L186

Therefore it would be good to be able to allow overriding of the Azure Resource Group location by specifying an $env: parameter which could be set via AppVeyor.yml.

I can submit a PR for this as well.

**Comment by johlju** [comment]
I hit this too... Tried to add a VM to West US, but West US 2 seems to work. To bad I could create storage account in West US. :) Have to re-create that.

![image](https://user-images.githubusercontent.com/7189721/28818426-6637a304-76ab-11e7-9e2c-a57a86575665.png)
